function scenarios = make_scenarios()
%MAKE_SCENARIOS Fixed ablation groups for the near-field tracker.
%
% The default hardware configuration is 3-bit, but the final tracking
% comparison needs explicit 1/2/3-bit quantized cases.  Each scenario can
% therefore carry a phase_bits override; NaN means "continuous beam".

scenarios = [ ...
    make_scenario('ideal', 'Ideal continuous', ...
        false, true, false, false, NaN), ...
    make_scenario('uncompensated', 'Impaired uncompensated (3-bit)', ...
        true, false, true, false, 3), ...
    make_scenario('rf_only', 'RF compensation continuous', ...
        true, true, false, false, NaN), ...
    make_scenario('quant_only_1bit', 'Quantization-aware only (1-bit)', ...
        false, true, true, true, 1), ...
    make_scenario('quant_only_2bit', 'Quantization-aware only (2-bit)', ...
        false, true, true, true, 2), ...
    make_scenario('quant_only', 'Quantization-aware only (3-bit)', ...
        false, true, true, true, 3), ...
    make_scenario('rf_quant_naive_1bit', 'RF comp + naive quant. (1-bit)', ...
        true, true, true, false, 1), ...
    make_scenario('rf_quant_naive_2bit', 'RF comp + naive quant. (2-bit)', ...
        true, true, true, false, 2), ...
    make_scenario('rf_quant_naive', 'RF comp + naive quant. (3-bit)', ...
        true, true, true, false, 3), ...
    make_scenario('joint_1bit', 'Joint robust tracking (1-bit)', ...
        true, true, true, true, 1), ...
    make_scenario('joint_2bit', 'Joint robust tracking (2-bit)', ...
        true, true, true, true, 2), ...
    make_scenario('joint', 'Joint robust tracking (3-bit)', ...
        true, true, true, true, 3) ...
    ];
end

function scenario = make_scenario(name, label, physical_rf, model_rf, quantized, robust, phase_bits)
scenario = struct( ...
    'name', name, ...
    'label', label, ...
    'physical_rf', physical_rf, ...
    'model_rf', model_rf, ...
    'quantized', quantized, ...
    'robust', robust, ...
    'phase_bits', phase_bits);
end
