function scenarios = make_scenarios()
%MAKE_SCENARIOS Fixed ablation groups for the near-field tracker.

scenarios = [ ...
    struct('name', 'ideal', 'label', '理想硬件连续波束', ...
        'physical_rf', false, 'model_rf', true, 'quantized', false, 'robust', false), ...
    struct('name', 'uncompensated', 'label', '受损未补偿', ...
        'physical_rf', true, 'model_rf', false, 'quantized', true, 'robust', false), ...
    struct('name', 'rf_only', 'label', '仅射频补偿', ...
        'physical_rf', true, 'model_rf', true, 'quantized', false, 'robust', false), ...
    struct('name', 'quant_only', 'label', '仅量化感知', ...
        'physical_rf', false, 'model_rf', true, 'quantized', true, 'robust', true), ...
    struct('name', 'rf_quant_naive', 'label', '射频补偿+朴素量化', ...
        'physical_rf', true, 'model_rf', true, 'quantized', true, 'robust', false), ...
    struct('name', 'joint', 'label', '联合算法', ...
        'physical_rf', true, 'model_rf', true, 'quantized', true, 'robust', true) ...
    ];
end
